
   - name: play1
     hosts: all
     tasks:
     
     - name: Task of play1
       ansible.builtin.debug:
        msg: "Hello world"

     - name: Task2 of play1
       ansible.builtin.ping:
        
        

