
   - name: play1
     hosts: all
     tasks:
     - name: Task of play1
       ansible.builtin.debug:
        msg: "Hello world"
     - name: Task of play2
       ansible.builtin.ping:
        ping: pong
        

