
- name: play1
  hosts: all
  tasks:
  - name: Task of play1
    ansible.builtin.debug:
      msg: "Hello world"

  - name: Task2 of play1
    ansible.builtin.ping:

-  name: Play2
   hosts: prod
   tasks: 
    - name: task1 of Play2
      ansible.builtin.debug:
        msg: "Hi this is prod"
    - name: task2 of Play2
      ansible.builtin.shell:
        cmd: df -h

- name: Play3
  hosts: dev
  tasks: 
  - name: task1 of Play3
    ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
     dest: /home/ec2-user/ 
          

        

