
- name: play1
  hosts: all
  tasks:
  - name: Task of play1
    ansible.builtin.debug:
      msg: "Hello world"

  - name: Task2 of play1
    ansible.builtin.ping:

-  name: Play2
   hosts: prod
   tasks: 
    - name: taks1 of Play2
      ansible.builtin.debug:
        msg: "Hi this is prod"
    - name: task2 of Play2
      ansible.builtin.shell:
       cmd: df -h

        

