- name: Printing the content
  hosts: prod
  vars_files:
    - "{{ ENV }}files.yaml"
  tasks:
    - name: Printing the variables from play
      ansible.builtin.debug:
       msg: "This is the value of {{ ENV }} and the team_lead is {{ TEAMLEAD }} of the value is {{ A }}"