- name: play1 of gathering facts
  hosts: all
  gather_facts: no
  tasks:
   - name: Display of hostname and os
     ansible.builtin.debug:
      msg: 
          "Hostname: {{ ansible_hostname }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"