- name: Gathering the facts
  hosts: all
  tasks: 
   - name: gather the facts
     ansible.builtin.debug:
      msg: |
          "Hostname: {{ ansible_hostname }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
