- name: variables test
  hosts: all
  vars:
   url: https://www.localhost.com
  tasks:
   - name: printing the play variable
     ansible.builtin.debug:
      msg: "This is a play variable {{ url }}"

   - name: printing the local variable
     ansible.builtin.debug:
      msg: "This is a local variable {{ link }}"
     vars:
      link: https://www.localhost1.com