- name: using the shell 
  hosts: prod
  tasks:
   - name: task1 of shell 
     ansible.builtin.shell: uptime
     register: OUT
     
   - name: printing the variable
     ansible.builtin.debug:
      vars: OUT.stdout