- name: demo on using errors
  hosts: all
  tasks: 
   - name: check python is present or not
     ansible.builtin.shell: ps -ef | grep python | grep -v grep

   - name: Task2 of play1
     ansible.builtin.shell: ps -ef
