
- name: creating a {{ app_user }}
  ansible.builtin.user:
   name: "{{ app_user }}"


- name: deleting the application directory
  ansible.builtin.file:
   name: "{{ app_dir }}"
   state: absent


- name: creating the directory
  ansible.builtin.file:
   name: "{{ app_dir }}"
   state: directory

- name: downloading and extracting the {{ component }} code
  ansible.builtin.unarchive: 
   src: "{{ url }}"
   dest: "{{ app_dir }}"
   remote_src: yes