- name: configuring the {{ component }} hostname
  ansible.builtin.shell: set-hostname {{ component }}


- name: Installing {{ component }}
  ansible.builtin.package:
   name: "{{ component }}"
   state: present

- name: Starting {{ component }} service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes 

- name: setting the password for {{ component }}
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1
  